### ISSUE TITLE
Refactor with Next.js

### ISSUE THREAD

**Issue by abkfenris** [gulfofmaine/Neracoos-1-Buoy-App#2494]
Refactor to use Next.js
```[tasklist]
### Tasks
- [x] Fix test suite
- [x] Launch to dev with SPA/React-Router based routing
- [x] Migrate about page to app based routing
- [ ] https://github.com/gulfofmaine/Neracoos-1-Buoy-App/issues/2640
- [x] Migrate platform pages to app based routing
- [x] Migrate home page to app based routing
- [ ] Progressively convert elements to enable server side rendering
```

**Comment by abkfenris** [comment]
Cookies for unit and datum state/preferences
- https://nextjs.org/docs/app/api-reference/functions/cookies
- https://github.com/vercel/next.js/discussions/54906
- https://developer.mozilla.org/en-US/docs/Web/HTTP/Cookies

**Comment by abkfenris** [comment]
[Suspense](https://react.dev/reference/react/Suspense) for creating hybrid server/client components that are progressively enhanced.

**Comment by abkfenris** [comment]
- https://web.archive.org/web/20230320011125/https://nextjs.org/docs/migrating/from-react-router
- https://nextjs.org/docs/app/building-your-application/upgrading/app-router-migration

**Comment by abkfenris** [comment]
Took care of platforms and index with #2627 but ended up disabling Cypress in the process due to some React issues #2638

**Comment by abkfenris** [comment]
Using <Suspense> for client only components: https://react.dev/reference/react/Suspense#providing-a-fallback-for-server-errors-and-client-only-content
