### ISSUE TITLE
Water Level Page

### ISSUE THREAD

**Issue by Adelle-Pitsas** [gulfofmaine/Neracoos-1-Buoy-App#2701]
```[tasklist]
### Tasks
- [ ] Add new page "Water Level"
- [ ] Mimic layout to what currently exists in Mariners and what was [sketched out](https://gmri.app.box.com/file/1376106683171)
- [ ] Pull in preliminary data into a chart
- [ ] Add standard references in graph (I don't fully know what these are and should be yet)
- [ ] Add ability to switch datums (2nd iteration of project)
```

**Comment by youngmorse** [comment]
Since the WL product requirements are starting coalesce in the CIVIC Box folder I'll just add a few more links vs. recreating so we don't have to update in more than one place. Hannah made a V2 of the Product Requirements doc to outline basic functionality for both the NERACOOS/Mariners viewer and the EcoINet viewer: [CIVIC WL Products](https://gmri.box.com/s/hfgfufhm02jfbh5dfjp52p3npw9n6yp5)

Somewhere in that doc is a link to 'data sources' which is a Google sheet where I started compiling the info on the gauges/sensors - including the benchmark references for flooding levels that will end up on the charts: [Google Sheet w/Sensor Info](https://docs.google.com/spreadsheets/d/1drNVI256jN8VGVP4-Iwym3H6Fqlpw2DGBXwmPXWjBjA/edit?usp=sharing)

Revised sketch up of product:
![IMG_4724](https://github.com/gulfofmaine/Neracoos-1-Buoy-App/assets/3279645/89f89049-66a8-492b-85b8-bcc81ad92874)

An example on [NOAA Inundation Dashboard](https://tidesandcurrents.noaa.gov/inundationdb/inundation.html?id=8418150&units=standard&bdate=20231205&edate=20231207&timezone=LST/LDT&datum=MLLW&interval=6&action=) of a chart (also in [HighCharts](https://www.highcharts.com/)!) that shows the benchmarks for flooding levels:
<img width="1031" alt="Screen Shot 2023-12-06 at 3 43 39 PM" src="https://github.com/gulfofmaine/Neracoos-1-Buoy-App/assets/3279645/4cb2f486-f035-4230-861e-11d461dbc09e">

**Comment by tshyka** [comment]
Thanks for sharing these docs. Can you provide access to the CIVIC Box folder?

**Comment by youngmorse** [comment]
Hi Tom, I don't think I can't share the Box links because you are outside of GMRI but I'll send it to you. It's a cleaned up version of our WL product requirements from Google Docs.

**Comment by Adelle-Pitsas** [comment]
There has been discussion about how and where different selectors are located and displayed. There have been a few iterations of this and screenshots can be found in [#2803 ](https://github.com/gulfofmaine/Neracoos-1-Buoy-App/pull/2803) and in PR [#2811](https://github.com/gulfofmaine/Neracoos-1-Buoy-App/pull/2811). In addition to the layout changes in these screenshots, the datum selection was moved from a dropdown to a radio button group. There was also discussion of the datum selection being a button group. 
Examples of each selector style:
Dropdown:
![Screenshot 2024-04-10 at 10 36 43 AM](https://github.com/gulfofmaine/Neracoos-1-Buoy-App/assets/108096652/9bae502f-59e7-4766-9b8e-f2798aa92963)
Radio group:
![Screenshot 2024-04-10 at 10 37 10 AM](https://github.com/gulfofmaine/Neracoos-1-Buoy-App/assets/108096652/06778cd3-1f36-447b-b9d6-fa7125ed3758)
Button group:
![Screenshot 2024-04-10 at 10 37 53 AM](https://github.com/gulfofmaine/Neracoos-1-Buoy-App/assets/108096652/d4de4d5e-ec3a-4b5f-a5c6-c630684dac01)

**Comment by youngmorse** [comment]
I've been finding a few bugs while adding sensors. I'm adding them as comments w/detail then they can go up to the task list or promoted to new issues if needed. 

- [ ] The y-axis range is really big, it's more noticeable on the sensors with the smaller ranges. It does appear to be scaling dynamically but the range is too big. 
<img width="1231" alt="Y-axis_range" src="https://github.com/gulfofmaine/Neracoos-1-Buoy-App/assets/3279645/c6c9de79-1b18-444d-bd74-37f9271cee92">

<img width="924" alt="Y-axis_range2" src="https://github.com/gulfofmaine/Neracoos-1-Buoy-App/assets/3279645/d12f62e5-ff79-46ad-a454-11e0bb930b11">

**Comment by youngmorse** [comment]
- [ ] Unit system selection reverts back to English from Metric when you change stations or change time range. Works okay with Datum selection change (hard to show in a screen shot but easy to replicate!)
<img width="546" alt="Screenshot 2024-04-12 at 4 20 53 PM" src="https://github.com/gulfofmaine/Neracoos-1-Buoy-App/assets/3279645/3e930fa4-e4da-46ac-87fd-1e7bd3fb7ef0">
<img width="469" alt="Screenshot 2024-04-12 at 4 21 02 PM" src="https://github.com/gulfofmaine/Neracoos-1-Buoy-App/assets/3279645/bf91b59c-fe44-4e11-b4cb-19b124686f9e">

**Comment by youngmorse** [comment]
A couple of timeframe date select bugs (Firefox)

- [ ] If you change the time range it retains the setting if you change platforms on that page. The URL stays the same as the selected range. Refreshing the browser doesn't reset to the default range, you have to click the 'Water Level' link in the menu and select a station to reset the range. (My first movie was too big to upload but shows the behavior a little more clearly.)

https://github.com/gulfofmaine/Neracoos-1-Buoy-App/assets/3279645/a6f012c3-3465-4087-bcaa-0b51e6d36921



- [ ] If you use the calendar option the dates change fine. If you try to type a new date the fields disappear!


https://github.com/gulfofmaine/Neracoos-1-Buoy-App/assets/3279645/7a71f6a8-1da8-4a6a-a062-818c7daa9eab

**Comment by youngmorse** [comment]
These two are related to the marker status if flood levels are detected:

- [ ]  On the [Water Level landing page](https://mariners-dev.aws.neracoos.org/water-level), the flood marker color doesn't change for CASM1 to show Moderate but the tooltip shows that it's moderate. It did change to show markers with Action level for stations further south (CT)
<img width="759" alt="Marker_not_showing_flood" src="https://github.com/gulfofmaine/Neracoos-1-Buoy-App/assets/3279645/6fef2533-d29c-48f7-b19d-8ab5362ea468">

![action_flood_marker](https://github.com/gulfofmaine/Neracoos-1-Buoy-App/assets/3279645/6693e2fc-f4bd-43f3-9ddb-4d01e0245abb)


- [ ]  This shows the CASM1 station detail page does change color for moderate flooding. (note: I temporarily lowered the flood benchmarks at this station to show a moderate flood level)
<img width="1398" alt="Moderate_flood_marker" src="https://github.com/gulfofmaine/Neracoos-1-Buoy-App/assets/3279645/c9ff1bf7-98f9-44b4-ae11-8ffb2a384779">

**Comment by youngmorse** [comment]
These next few are enhancements not bugs...

New features/behaviors:
- [ ] Add vertical line to show current time on plot

Changes to current features/behavior (open to discussion)

- [ ] Default time is GMT - do we want to convert to EST?
<img width="958" alt="timestamp_GMT" src="https://github.com/gulfofmaine/Neracoos-1-Buoy-App/assets/3279645/917ea4f4-91f5-4bf5-b5c5-b40cc20679da">

- [ ] For stations with not a lot of difference in benchmarks, it's hard to see the difference in the two levels. the https://water.noaa.gov has this problem too, so it may be a tough one to solve. 
<img width="943" alt="Benchmarks_too_close" src="https://github.com/gulfofmaine/Neracoos-1-Buoy-App/assets/3279645/02ac184c-f3c9-444b-8b62-348d314f23b8">

- [ ] For stations that have a lot of additional data do we want to limit what we show in the station info? Noticed this on a station that had 6-7 variables.

<img width="445" alt="Screenshot 2024-04-12 at 5 13 43 PM" src="https://github.com/gulfofmaine/Neracoos-1-Buoy-App/assets/3279645/783b1f03-3034-410e-8665-73d336e51267">
